name: Sample

on:
  push: {branches: main}
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
      - uses: actions/checkout@v3
      - name: "check rss"
        id: "check"
        uses: tamanishi/gh-action-rss@v0.13
      - name: "update page"
        if: steps.check.outputs.result == 'updated'
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/tamanishi/rebuildshownotesfilter-nextjs/dispatches" -d '{"event_type": "update-episodes"}'
      - name: "commit rss"
        if: steps.check.outputs.result == 'updated'
        run: |
          git add ./rss.xml
          git config user.name "Masayuki Sunahara"
          git config user.email tamanishi@gmail.com
          git commit -m "update episodes"
          git push origin main
