name: Sample

on:
  push: {branches: main}
  pull_request: {branches: main}
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
      - uses: actions/checkout@v3
      - name: "check rss"
        id: "check"
        uses: tamanishi/gh-action-rss@v0.11
      - name: "commit rss"
        run: |
          git add ./rss.xml
          git config user.name "Masayuki Sunahara"
          git config user.email tamanishi@gmail.com
          git commit -m "update episodes"
      - name: "head rss"
        run: head -n 10 ./rss.xml
      - name: "tail rss"
        run: tail -n 10 ./rss.xml
